name: Generate Debian Package

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: sudo pip install pipenv2deb==2.0.7
      - name: Generate Debian Package
        run: sudo python3 -m pipenv2deb
      - name: Upload Debian Package
        uses: actions/upload-artifact@v3
        with:
          name: debian-package
          path: packages/*.deb
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: packages/*.deb
